### ISSUE TITLE
No data is shown after import

### ISSUE THREAD

**Issue by awaisas** [Yooooomi/your_spotify#203] opened 2023-02-12 03:02 UTC
**Describe the bug**
After importing the full streaming history. It is showing as successfully imported but no statistics shows the imported data. The docker log for the server shows the data being imported (when the importing was happening).

**Expected behavior**
The app showing the statistics.

**Additional context**
Docker on a Ubuntu server.
Interacting with the web page from Safari on macOS.

**Comment by Yooooomi** [comment] 2023-02-12 07:52
Hello! Can you check you are using the latest version? This seems to me like a duplicate of #202

**Comment by awaisas** [comment] 2023-02-12 11:07
Thank you. That seemed to fix it! :)

**Closed** 2023-02-12 11:24 UTC
