### ISSUE TITLE
Feature Request - date format setting

### ISSUE THREAD

**Issue by clearlynotstefan** [Yooooomi/your_spotify#376] opened 2024-03-19 17:30 UTC
Would it be possible to include a setting that allows customization of datetime formatting, or even just a checkbox that changes d/m/yyyy to m/d/yyyy? Yes I agree American formatting is weird on this but it's what we're used to 😅

**Comment by Yooooomi** [comment] 2024-03-19 19:28
Hello! Working on it, marking this as duplicate of #322

**Closed by Yooooomi** 2024-03-19 19:28 UTC
